import { defineConfig } from "astro/config";
import node from "@astrojs/node";

export default defineConfig({
  adapter: node({ mode: "standalone" }),
  site: "https://plata.today",
  vite: {
    envDir: "../../",
  },
  i18n: {
    defaultLocale: "en",
    locales: [
      "ar",
      "bn",
      "ca",
      "zh",
      "zh-tw",
      "cs",
      "da",
      "nl",
      "en",
      "fa",
      "fi",
      "fr",
      "de",
      "el",
      "he",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "ms",
      "no",
      "pl",
      "pt",
      "ro",
      "ru",
      "es",
      "sw",
      "sv",
      "tl",
      "th",
      "tr",
      "uk",
      "ur",
      "vi",
    ],
    routing: {
      prefixDefaultLocale: true,
    },
  },
});
