export const LANGUAGES = {
  ar: { name: "Arabic", nativeName: "العربية", flag: "🇸🇦", tier: 3 },
  zh: { name: "Chinese", nativeName: "中文", flag: "🇨🇳", tier: 2 },
  da: { name: "Danish", nativeName: "Dansk", flag: "🇩🇰", tier: 3 },
  nl: { name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱", tier: 3 },
  en: { name: "English", nativeName: "English", flag: "🇬🇧", tier: 1 },
  fi: { name: "Finnish", nativeName: "Suomi", flag: "🇫🇮", tier: 3 },
  fr: { name: "French", nativeName: "Français", flag: "🇫🇷", tier: 1 },
  de: { name: "German", nativeName: "Deutsch", flag: "🇩🇪", tier: 1 },
  el: { name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷", tier: 3 },
  hi: { name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", tier: 3 },
  id: { name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩", tier: 3 },
  it: { name: "Italian", nativeName: "Italiano", flag: "🇮🇹", tier: 1 },
  ja: { name: "Japanese", nativeName: "日本語", flag: "🇯🇵", tier: 2 },
  ko: { name: "Korean", nativeName: "한국어", flag: "🇰🇷", tier: 2 },
  no: { name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴", tier: 3 },
  pl: { name: "Polish", nativeName: "Polski", flag: "🇵🇱", tier: 2 },
  pt: { name: "Portuguese", nativeName: "Português", flag: "🇧🇷", tier: 1 },
  ru: { name: "Russian", nativeName: "Русский", flag: "🇷🇺", tier: 2 },
  es: { name: "Spanish", nativeName: "Español", flag: "🇪🇸", tier: 2 },
  sw: { name: "Swahili", nativeName: "Kiswahili", flag: "🇰🇪", tier: 3 },
  sv: { name: "Swedish", nativeName: "Svenska", flag: "🇸🇪", tier: 3 },
  th: { name: "Thai", nativeName: "ไทย", flag: "🇹🇭", tier: 3 },
  tr: { name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷", tier: 3 },
  uk: { name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦", tier: 2 },
  vi: { name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳", tier: 3 },
} as const;

export type LangCode = keyof typeof LANGUAGES;
export const LANG_CODES = Object.keys(LANGUAGES) as LangCode[];
